id: P007044
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:38:08.234263
source_metadata:
  id: bdr:W28952
  title: ཤེས་བྱའི་རྣམ་གྲངས་བློ་གསལ་རིགས་སྒོ
  author: ''
  volumes:
    fe6b98e869c54233b164c680e4c962b0:
      image_group_id: I4963
      title: ''
      volume_number: 1
      total_pages: 212
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
