id: P007044
initial_creation_type: ocr
source_metadata:
  id: bdr:W28952
  title: ཤེས་བྱའི་རྣམ་གྲངས་བློ་གསལ་རིགས་སྒོ
  author: ''
  volumes:
    fe6b98e869c54233b164c680e4c962b0:
      image_group_id: I4963
      title: ''
      volume_number: 1
      total_pages: 212
ebook_metadata:
  title: ཤེས་བྱའི་རྣམ་གྲངས་བློ་གསལ་རིགས་སྒོ
  author: ''
  sku: P007044
  cover: cover.jpg
  layers:
  - pagination
