id: I8AA22893
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:09:25+00:00'
last_modified: '2022-06-08T16:14:17.782596+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28952
  title: ཤེས་བྱའི་རྣམ་གྲངས་བློ་གསལ་རིགས་སྒོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D931:
      image_group_id: I4963
      title: ''
      total_pages: 212
      order: 1
      base_file: D931.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
